-- Restaurant Ordering & Kitchen Display: database for Supabase.
--
-- Run once in Supabase: Dashboard -> SQL Editor -> New query -> paste this whole file -> Run.
-- It is safe to run again: nothing is dropped, and the menu and tables are only added when empty.
--
-- Every table and index starts with babji_RestaurantKitchen_ so this app can share a Supabase
-- project with other apps. The names are in double quotes so Postgres keeps the capital letters;
-- when you query them yourself, quote them too, e.g.  SELECT * FROM "babji_RestaurantKitchen_orders";
--
-- Money is in rupees with 2 decimals (NUMERIC(10,2), e.g. 480.00). Timestamps are milliseconds since 1970 (BIGINT).
-- Must match src/schema.js (the app creates the same tables itself if they are missing).

BEGIN;

-- ---------------------------------------------------------------- tables

CREATE TABLE IF NOT EXISTS "babji_RestaurantKitchen_menu_categories" (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT    NOT NULL,
  sort_order  INTEGER NOT NULL DEFAULT 0,
  archived_at BIGINT
);

CREATE TABLE IF NOT EXISTS "babji_RestaurantKitchen_menu_items" (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id  INTEGER NOT NULL REFERENCES "babji_RestaurantKitchen_menu_categories"(id),
  name         TEXT    NOT NULL,
  price        NUMERIC(10, 2) NOT NULL CHECK (price >= 0),  -- rupees, e.g. 480.00
  is_veg       INTEGER NOT NULL DEFAULT 1 CHECK (is_veg IN (0, 1)),
  prep_minutes INTEGER NOT NULL DEFAULT 10 CHECK (prep_minutes >= 0),
  is_available INTEGER NOT NULL DEFAULT 1 CHECK (is_available IN (0, 1)),
  emoji        TEXT    NOT NULL DEFAULT '',  -- the dish's mini picture on the menu
  photo        TEXT    NOT NULL DEFAULT '',  -- photo file in public/img/menu/, '' = show the emoji
  archived_at  BIGINT                        -- items are archived, never deleted
);

CREATE TABLE IF NOT EXISTS "babji_RestaurantKitchen_tables" (
  id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number INTEGER NOT NULL UNIQUE,
  seats  INTEGER NOT NULL DEFAULT 4
);

CREATE TABLE IF NOT EXISTS "babji_RestaurantKitchen_bills" (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_id       INTEGER NOT NULL REFERENCES "babji_RestaurantKitchen_tables"(id),
  subtotal       NUMERIC(12, 2) NOT NULL,  -- rupees, before GST
  gst            NUMERIC(12, 2) NOT NULL,
  total          NUMERIC(12, 2) NOT NULL,
  closed_at      BIGINT  NOT NULL
);

-- A table is "occupied" while it has orders with paid_at IS NULL.
CREATE TABLE IF NOT EXISTS "babji_RestaurantKitchen_orders" (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_id     INTEGER NOT NULL REFERENCES "babji_RestaurantKitchen_tables"(id),
  status       TEXT    NOT NULL DEFAULT 'New'
               CHECK (status IN ('New', 'Preparing', 'Ready', 'Served')),
  placed_at    BIGINT  NOT NULL,
  preparing_at BIGINT,
  ready_at     BIGINT,
  served_at    BIGINT,
  paid_at      BIGINT,
  bill_id      INTEGER REFERENCES "babji_RestaurantKitchen_bills"(id)
);

-- item_name and unit_price_at_order are snapshots taken when the line is added,
-- so later menu edits never change a placed order.
CREATE TABLE IF NOT EXISTS "babji_RestaurantKitchen_order_items" (
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id            INTEGER NOT NULL REFERENCES "babji_RestaurantKitchen_orders"(id) ON DELETE CASCADE,
  item_id             INTEGER NOT NULL REFERENCES "babji_RestaurantKitchen_menu_items"(id),
  item_name           TEXT    NOT NULL,
  qty                 INTEGER NOT NULL CHECK (qty > 0),
  note                TEXT    NOT NULL DEFAULT '',
  unit_price_at_order NUMERIC(10, 2) NOT NULL CHECK (unit_price_at_order >= 0),  -- rupees
  added_at            BIGINT  NOT NULL
);

-- 'version' is the live-sync change counter; 'schema' is the schema version the app checks.
CREATE TABLE IF NOT EXISTS "babji_RestaurantKitchen_app_state" (
  name TEXT PRIMARY KEY,
  num  BIGINT NOT NULL
);

-- Wrong-PIN counter per client address (locked for a minute after 5 tries).
CREATE TABLE IF NOT EXISTS "babji_RestaurantKitchen_login_failures" (
  ip       TEXT PRIMARY KEY,
  failures INTEGER NOT NULL,
  until_at BIGINT  NOT NULL
);

-- ---------------------------------------------------------------- indexes

CREATE INDEX IF NOT EXISTS "babji_RestaurantKitchen_idx_orders_open"
  ON "babji_RestaurantKitchen_orders"(table_id) WHERE paid_at IS NULL;
CREATE INDEX IF NOT EXISTS "babji_RestaurantKitchen_idx_orders_active"
  ON "babji_RestaurantKitchen_orders"(status, placed_at) WHERE status <> 'Served';
CREATE INDEX IF NOT EXISTS "babji_RestaurantKitchen_idx_orders_placed"
  ON "babji_RestaurantKitchen_orders"(placed_at);
CREATE INDEX IF NOT EXISTS "babji_RestaurantKitchen_idx_orders_ready"
  ON "babji_RestaurantKitchen_orders"(ready_at);
CREATE INDEX IF NOT EXISTS "babji_RestaurantKitchen_idx_order_items_ord"
  ON "babji_RestaurantKitchen_order_items"(order_id);
CREATE INDEX IF NOT EXISTS "babji_RestaurantKitchen_idx_order_items_item"
  ON "babji_RestaurantKitchen_order_items"(item_id);
CREATE INDEX IF NOT EXISTS "babji_RestaurantKitchen_idx_bills_closed"
  ON "babji_RestaurantKitchen_bills"(closed_at);
CREATE INDEX IF NOT EXISTS "babji_RestaurantKitchen_idx_items_category"
  ON "babji_RestaurantKitchen_menu_items"(category_id);

-- ---------------------------------------------------------------- paise -> rupees
-- Databases created before this change stored money as whole paise (48000) in *_paise columns.
-- This converts them in place to rupees (480.00). It does nothing on a database that is already
-- in rupees, so it is safe to run again. (The app does the same conversion on its own at start.)

DO $$
DECLARE
  c RECORD;
BEGIN
  FOR c IN SELECT * FROM (VALUES
      ('babji_RestaurantKitchen_menu_items',  'price_paise',         'price',               10),
      ('babji_RestaurantKitchen_order_items', 'unit_price_at_order', 'unit_price_at_order', 10),
      ('babji_RestaurantKitchen_bills',       'subtotal_paise',      'subtotal',            12),
      ('babji_RestaurantKitchen_bills',       'gst_paise',           'gst',                 12),
      ('babji_RestaurantKitchen_bills',       'total_paise',         'total',               12)
    ) AS m(tbl, old_col, new_col, prec)
  LOOP
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_schema = current_schema() AND table_name = c.tbl
                 AND column_name = c.old_col AND data_type = 'integer') THEN
      IF c.old_col <> c.new_col THEN
        EXECUTE format('ALTER TABLE %I RENAME COLUMN %I TO %I', c.tbl, c.old_col, c.new_col);
      END IF;
      EXECUTE format('ALTER TABLE %I ALTER COLUMN %I TYPE NUMERIC(%s, 2) USING %I / 100.0',
                     c.tbl, c.new_col, c.prec, c.new_col);
    END IF;
  END LOOP;
END $$;

-- ---------------------------------------------------------------- dish photos
-- Databases created before photos existed get the column, and each starting dish its photo
-- (public/img/menu/<dish-name>.jpg). Dishes added by the manager keep showing their emoji.

ALTER TABLE "babji_RestaurantKitchen_menu_items" ADD COLUMN IF NOT EXISTS photo TEXT NOT NULL DEFAULT '';

UPDATE "babji_RestaurantKitchen_menu_items"
SET photo = trim(both '-' from regexp_replace(lower(name), '[^a-z0-9]+', '-', 'g')) || '.jpg'
WHERE photo = '' AND name IN ('Paneer Tikka', 'Chicken 65', 'Veg Spring Rolls', 'Amritsari Fish', 'Butter Chicken',
  'Paneer Butter Masala', 'Dal Makhani', 'Mutton Rogan Josh', 'Veg Biryani', 'Chicken Biryani', 'Butter Naan', 'Garlic Naan',
  'Tandoori Roti', 'Gulab Jamun', 'Rasmalai', 'Masala Chai', 'Sweet Lassi', 'Fresh Lime Soda');

-- ---------------------------------------------------------------- security
-- Supabase exposes every table in "public" through its REST API to anyone holding the project's
-- anon key. Row level security with no policies blocks that completely. The app itself connects
-- with the database connection string (as the table owner), which row level security does not limit.

ALTER TABLE "babji_RestaurantKitchen_menu_categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "babji_RestaurantKitchen_menu_items"      ENABLE ROW LEVEL SECURITY;
ALTER TABLE "babji_RestaurantKitchen_tables"          ENABLE ROW LEVEL SECURITY;
ALTER TABLE "babji_RestaurantKitchen_bills"           ENABLE ROW LEVEL SECURITY;
ALTER TABLE "babji_RestaurantKitchen_orders"          ENABLE ROW LEVEL SECURITY;
ALTER TABLE "babji_RestaurantKitchen_order_items"     ENABLE ROW LEVEL SECURITY;
ALTER TABLE "babji_RestaurantKitchen_app_state"       ENABLE ROW LEVEL SECURITY;
ALTER TABLE "babji_RestaurantKitchen_login_failures"  ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------- starting data
-- Only added when the menu is empty, so running the script again never duplicates anything.

INSERT INTO "babji_RestaurantKitchen_menu_categories" (name, sort_order)
SELECT v.name, v.sort_order
FROM (VALUES ('Starters', 1), ('Mains', 2), ('Breads', 3), ('Desserts', 4), ('Beverages', 5)) AS v(name, sort_order)
WHERE NOT EXISTS (SELECT 1 FROM "babji_RestaurantKitchen_menu_categories");

INSERT INTO "babji_RestaurantKitchen_menu_items" (category_id, name, price, is_veg, prep_minutes, emoji, photo)
SELECT c.id, v.name, v.price, v.is_veg, v.prep_minutes, v.emoji,
       trim(both '-' from regexp_replace(lower(v.name), '[^a-z0-9]+', '-', 'g')) || '.jpg'
FROM (VALUES
  ('Starters',  'Paneer Tikka',         280.00, 1, 15, '🧀'),
  ('Starters',  'Chicken 65',           320.00, 0, 15, '🌶️'),
  ('Starters',  'Veg Spring Rolls',     220.00, 1, 10, '🌯'),
  ('Starters',  'Amritsari Fish',       380.00, 0, 15, '🐟'),
  ('Mains',     'Butter Chicken',       420.00, 0, 20, '🍗'),
  ('Mains',     'Paneer Butter Masala', 340.00, 1, 18, '🍲'),
  ('Mains',     'Dal Makhani',          280.00, 1, 15, '🥘'),
  ('Mains',     'Mutton Rogan Josh',    480.00, 0, 25, '🍖'),
  ('Mains',     'Veg Biryani',          300.00, 1, 20, '🍚'),
  ('Mains',     'Chicken Biryani',      380.00, 0, 22, '🍛'),
  ('Breads',    'Butter Naan',           60.00, 1,  5, '🫓'),
  ('Breads',    'Garlic Naan',           80.00, 1,  5, '🧄'),
  ('Breads',    'Tandoori Roti',         40.00, 1,  4, '🥙'),
  ('Desserts',  'Gulab Jamun',          120.00, 1,  3, '🍡'),
  ('Desserts',  'Rasmalai',             150.00, 1,  3, '🍮'),
  ('Beverages', 'Masala Chai',           60.00, 1,  4, '☕'),
  ('Beverages', 'Sweet Lassi',          110.00, 1,  3, '🥛'),
  ('Beverages', 'Fresh Lime Soda',       90.00, 1,  3, '🍋')
) AS v(category, name, price, is_veg, prep_minutes, emoji)
JOIN "babji_RestaurantKitchen_menu_categories" c ON c.name = v.category AND c.archived_at IS NULL
WHERE NOT EXISTS (SELECT 1 FROM "babji_RestaurantKitchen_menu_items");

-- Tables 1-12: 1-8 seat 4, 9-12 seat 6.
INSERT INTO "babji_RestaurantKitchen_tables" (number, seats)
SELECT n, CASE WHEN n <= 8 THEN 4 ELSE 6 END
FROM generate_series(1, 12) AS n
WHERE NOT EXISTS (SELECT 1 FROM "babji_RestaurantKitchen_tables");

INSERT INTO "babji_RestaurantKitchen_app_state" (name, num)
VALUES ('version', (EXTRACT(EPOCH FROM now()) * 1000)::BIGINT)
ON CONFLICT (name) DO NOTHING;

-- Tells the app the schema is already current (matches SCHEMA_VERSION in src/schema.js).
INSERT INTO "babji_RestaurantKitchen_app_state" (name, num)
VALUES ('schema', 4)
ON CONFLICT (name) DO UPDATE SET num = GREATEST("babji_RestaurantKitchen_app_state".num, excluded.num);

COMMIT;

-- Check: should list 8 tables, 18 menu items and 12 tables.
-- SELECT table_name FROM information_schema.tables WHERE table_name LIKE 'babji_RestaurantKitchen_%';
-- SELECT COUNT(*) FROM "babji_RestaurantKitchen_menu_items";
-- SELECT COUNT(*) FROM "babji_RestaurantKitchen_tables";
