'use strict';
// Schema, upgrades and seed data, shared by SQLite and Postgres.
// Money is integer paise; timestamps are integer milliseconds since the epoch.

const ddl = (dialect) => {
  const ID = dialect === 'postgres' ? 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' : 'INTEGER PRIMARY KEY';
  const TS = dialect === 'postgres' ? 'BIGINT' : 'INTEGER';
  return `
CREATE TABLE IF NOT EXISTS ${T.menu_categories} (
  id          ${ID},
  name        TEXT    NOT NULL,
  sort_order  INTEGER NOT NULL DEFAULT 0,
  archived_at ${TS}
);

CREATE TABLE IF NOT EXISTS ${T.menu_items} (
  id           ${ID},
  category_id  INTEGER NOT NULL REFERENCES ${T.menu_categories}(id),
  name         TEXT    NOT NULL,
  price_paise  INTEGER NOT NULL CHECK (price_paise >= 0),
  is_veg       INTEGER NOT NULL DEFAULT 1 CHECK (is_veg IN (0, 1)),
  prep_minutes INTEGER NOT NULL DEFAULT 10 CHECK (prep_minutes >= 0),
  is_available INTEGER NOT NULL DEFAULT 1 CHECK (is_available IN (0, 1)),
  emoji        TEXT    NOT NULL DEFAULT '',  -- the dish's mini picture on the menu
  -- Items are archived, never deleted, so historical order_items keep a valid FK.
  archived_at  ${TS}
);

CREATE TABLE IF NOT EXISTS ${T.tables} (
  id     ${ID},
  number INTEGER NOT NULL UNIQUE,
  seats  INTEGER NOT NULL DEFAULT 4
);

CREATE TABLE IF NOT EXISTS ${T.bills} (
  id             ${ID},
  table_id       INTEGER NOT NULL REFERENCES ${T.tables}(id),
  subtotal_paise INTEGER NOT NULL,
  gst_paise      INTEGER NOT NULL,
  total_paise    INTEGER NOT NULL,
  closed_at      ${TS} NOT NULL
);

-- A table is "occupied" while it has orders with paid_at IS NULL.
-- There is deliberately no separate occupied flag that could drift out of sync.
CREATE TABLE IF NOT EXISTS ${T.orders} (
  id           ${ID},
  table_id     INTEGER NOT NULL REFERENCES ${T.tables}(id),
  status       TEXT    NOT NULL DEFAULT 'New'
               CHECK (status IN ('New', 'Preparing', 'Ready', 'Served')),
  placed_at    ${TS} NOT NULL,
  preparing_at ${TS},
  ready_at     ${TS},
  served_at    ${TS},
  paid_at      ${TS},
  bill_id      INTEGER REFERENCES ${T.bills}(id)
);

-- item_name and unit_price_at_order are snapshots taken when the line is added.
-- Later menu edits (price change, rename, marked unavailable) never touch them.
CREATE TABLE IF NOT EXISTS ${T.order_items} (
  id                  ${ID},
  order_id            INTEGER NOT NULL REFERENCES ${T.orders}(id) ON DELETE CASCADE,
  item_id             INTEGER NOT NULL REFERENCES ${T.menu_items}(id),
  item_name           TEXT    NOT NULL,
  qty                 INTEGER NOT NULL CHECK (qty > 0),
  note                TEXT    NOT NULL DEFAULT '',
  unit_price_at_order INTEGER NOT NULL CHECK (unit_price_at_order >= 0),
  added_at            ${TS} NOT NULL
);

-- Change counter for live sync: every write bumps it, screens refetch when it moves.
CREATE TABLE IF NOT EXISTS ${T.app_state} (
  name TEXT PRIMARY KEY,
  num  ${TS} NOT NULL
);

-- Wrong-PIN counter per client address (lockout after 5 tries), shared by all servers.
CREATE TABLE IF NOT EXISTS ${T.login_failures} (
  ip       TEXT PRIMARY KEY,
  failures INTEGER NOT NULL,
  until_at ${TS} NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_orders_open      ON orders(table_id) WHERE paid_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_orders_active    ON orders(status, placed_at) WHERE status <> 'Served';
CREATE INDEX IF NOT EXISTS idx_orders_placed    ON orders(placed_at);
CREATE INDEX IF NOT EXISTS idx_orders_ready     ON orders(ready_at);
CREATE INDEX IF NOT EXISTS idx_order_items_ord  ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_item ON order_items(item_id);
CREATE INDEX IF NOT EXISTS idx_bills_closed     ON bills(closed_at);
CREATE INDEX IF NOT EXISTS idx_items_category   ON menu_items(category_id);
`;
};

// [name, rupees, is_veg, prep minutes, picture]
const SEED_MENU = [
  ['Starters', [
    ['Paneer Tikka', 280, 1, 15, '🧀'],
    ['Chicken 65', 320, 0, 15, '🌶️'],
    ['Veg Spring Rolls', 220, 1, 10, '🌯'],
    ['Amritsari Fish', 380, 0, 15, '🐟'],
  ]],
  ['Mains', [
    ['Butter Chicken', 420, 0, 20, '🍗'],
    ['Paneer Butter Masala', 340, 1, 18, '🍲'],
    ['Dal Makhani', 280, 1, 15, '🥘'],
    ['Mutton Rogan Josh', 480, 0, 25, '🍖'],
    ['Veg Biryani', 300, 1, 20, '🍚'],
    ['Chicken Biryani', 380, 0, 22, '🍛'],
  ]],
  ['Breads', [
    ['Butter Naan', 60, 1, 5, '🫓'],
    ['Garlic Naan', 80, 1, 5, '🧄'],
    ['Tandoori Roti', 40, 1, 4, '🥙'],
  ]],
  ['Desserts', [
    ['Gulab Jamun', 120, 1, 3, '🍡'],
    ['Rasmalai', 150, 1, 3, '🍮'],
  ]],
  ['Beverages', [
    ['Masala Chai', 60, 1, 4, '☕'],
    ['Sweet Lassi', 110, 1, 3, '🥛'],
    ['Fresh Lime Soda', 90, 1, 3, '🍋'],
  ]],
];
const SEED_EMOJI = new Map(SEED_MENU.flatMap(([, items]) => items.map((i) => [i[0], i[4]])));

// Creates tables, upgrades older databases in place, and seeds an empty one.
// Safe to run on every start. On Postgres an advisory lock stops two cold-starting
// serverless instances from seeding twice.
const SCHEMA_VERSION = 2; // bump when upgrade() learns something new

async function setup(db) {
  // Fast path for serverless cold starts: one query when the database is current.
  try {
    const rows = await db.query(`SELECT num FROM ${T.app_state} WHERE name = 'schema'`);
    if (rows[0] && Number(rows[0].num) >= SCHEMA_VERSION) return;
  } catch { /* app_state not created yet */ }

  if (db.dialect === 'postgres') {
    await db.tx(async (t) => {
      await t.query('SELECT pg_advisory_xact_lock(7201)');
      for (const stmt of ddl('postgres').split(';').map((s) => s.trim()).filter(Boolean)) await t.query(stmt);
      await upgrade(t);
      await seed(t);
    });
  } else {
    await db.exec(ddl('sqlite'));
    await db.tx(async (t) => { await upgrade(t); await seed(t); });
  }
}

async function upgrade(t) {
  const cols = (await t.query(t.dialect === 'postgres'
    ? 'SELECT column_name AS name FROM information_schema.columns WHERE table_name = $1'
    : 'SELECT name FROM pragma_table_info($1)', ['menu_items'])).map((c) => c.name);
  if (!cols.includes('emoji')) {
    await t.query("ALTER TABLE menu_items ADD COLUMN emoji TEXT NOT NULL DEFAULT ''");
    for (const [name, emoji] of SEED_EMOJI) {
      await t.query(`UPDATE ${T.menu_items} SET emoji = $1 WHERE name = $2 AND emoji = ''`, [emoji, name]);
    }
  }
  await t.query(`INSERT INTO ${T.app_state} (name, num) VALUES ('version', $1) ON CONFLICT (name) DO NOTHING`, [Date.now()]);
  await t.query(`INSERT INTO ${T.app_state} (name, num) VALUES ('schema', $1)
                 ON CONFLICT (name) DO UPDATE SET num = excluded.num`, [SCHEMA_VERSION]);
}

async function seed(t) {
  const [{ n }] = await t.query(`SELECT COUNT(*) AS n FROM ${T.menu_categories}`);
  if (Number(n) > 0) return;
  for (const [i, [category, items]] of SEED_MENU.entries()) {
    const [{ id: catId }] = await t.query(
      `INSERT INTO ${T.menu_categories} (name, sort_order) VALUES ($1, $2) RETURNING id`, [category, i + 1]);
    for (const [name, rupees, veg, prep, emoji] of items) {
      await t.query(`INSERT INTO ${T.menu_items} (category_id, name, price_paise, is_veg, prep_minutes, emoji)
                     VALUES ($1, $2, $3, $4, $5, $6)`, [catId, name, rupees * 100, veg, prep, emoji]);
    }
  }
  for (let n = 1; n <= 12; n++) {
    await t.query(`INSERT INTO ${T.tables} (number, seats) VALUES ($1, $2)`, [n, n <= 8 ? 4 : 6]);
  }
}

module.exports = { setup, SEED_MENU };
